// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_FILE_COMPRESSION_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_FILE_COMPRESSION_TYPE: i8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_FILE_COMPRESSION_TYPE: [FileCompressionType; 5] = [
  FileCompressionType::GZip,
  FileCompressionType::BZip2,
  FileCompressionType::Xz,
  FileCompressionType::ZStd,
  FileCompressionType::Uncompressed,
];

/// Readable file compression type.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct FileCompressionType(pub i8);
#[allow(non_upper_case_globals)]
impl FileCompressionType {
  /// Gzip-ed file.
  pub const GZip: Self = Self(0);
  /// Bzip2-ed file.
  pub const BZip2: Self = Self(1);
  /// Xz-ed file (liblzma).
  pub const Xz: Self = Self(2);
  /// Zstd-ed file.
  pub const ZStd: Self = Self(3);
  /// Uncompressed file.
  pub const Uncompressed: Self = Self(4);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::GZip,
    Self::BZip2,
    Self::Xz,
    Self::ZStd,
    Self::Uncompressed,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::GZip => Some("GZip"),
      Self::BZip2 => Some("BZip2"),
      Self::Xz => Some("Xz"),
      Self::ZStd => Some("ZStd"),
      Self::Uncompressed => Some("Uncompressed"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for FileCompressionType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for FileCompressionType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for FileCompressionType {
    type Output = FileCompressionType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for FileCompressionType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for FileCompressionType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for FileCompressionType {}
