// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod data_fusion_sharp {
  use super::*;
  pub mod formats {
    use super::*;
    pub mod csv {
      use super::*;
      mod csv_read_options_wire_generated;
      pub use self::csv_read_options_wire_generated::*;
    } // csv
    mod file_compression_type_generated;
    pub use self::file_compression_type_generated::*;
  } // formats
} // data_fusion_sharp
