using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DataFusionSharp.SourceGenerators;

/// <inheritdoc />
[Generator]
[ExcludeFromCodeCoverage]
public sealed class NativeCallbackGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "DataFusionSharp.Interop.DataFusionSharpNativeCallbackAttribute";

    private const string AttributeSource = """
        // <auto-generated>
        // Generated by DataFusionSharp.SourceGenerators.NativeCallbackGenerator.
        // Do not edit manually.
        // </auto-generated>
        namespace DataFusionSharp.Interop
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            internal sealed class DataFusionSharpNativeCallbackAttribute : global::System.Attribute { }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("DataFusionSharp.NativeCallbackAttribute.g.cs", AttributeSource));
        
        var callbacks = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax method &&
                    method.Modifiers.Any(SyntaxKind.StaticKeyword),
                transform: static (ctx, _) => ExtractCallbackDesc(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);
        
        context.RegisterSourceOutput(callbacks.Collect(), EmitSources);
    }

    private static void EmitSources(SourceProductionContext ctx, ImmutableArray<CallbackDesc> allCallbacks)
    {
        var callbacksByType = allCallbacks.GroupBy(m => m.TypeFullName, StringComparer.Ordinal);

        foreach (var callbacksInType in callbacksByType)
        {
            var callbacks = callbacksInType.ToImmutableArray();
            var fileName = $"DataFusionSharp.{callbacks.First().TypeName}.NativeCallbacks.g.cs";
            var source = GenerateSource(callbacks);
            ctx.AddSource(fileName, source);
        }
    }

    private static CallbackDesc? ExtractCallbackDesc(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method)
            return null;

        var type = method.ContainingType;
        if (type is null)
            return null;
        
        if (type.TypeKind != TypeKind.Class)
            return null;

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        var typeModifiers = GetTypeModifiers(type);
        var typeName = type.Name;

        return new CallbackDesc(ns, typeName, typeModifiers, method.Name, GetAccessibility(method.DeclaredAccessibility));
    }

    private static string GetTypeModifiers(INamedTypeSymbol type)
    {
        List<string> parts = [GetAccessibility(type.DeclaredAccessibility)];

        switch (type)
        {
            case { IsStatic: true }:
                parts.Add("static");
                break;
            case { IsSealed: true }:
                parts.Add("sealed");
                break;
            case { IsAbstract: true }:
                parts.Add("abstract");
                break;
        }

        parts.Add("partial");
        parts.Add("class");

        return string.Join(" ", parts);
    }
    
    private static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => "private"
    };

    private static string GenerateSource(ImmutableArray<CallbackDesc> callbacks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by DataFusionSharp.SourceGenerators.NativeCallbackGenerator.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        
        var anyCallback= callbacks.First();
        var hasNamespace = !string.IsNullOrEmpty(anyCallback.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine("namespace " + anyCallback.Namespace);
            sb.AppendLine("{");
        }

        var typeIndent = hasNamespace ? "    " : "";
        var memberIndent = hasNamespace ? "        " : "    ";

        sb.AppendLine(typeIndent + anyCallback.TypeModifiers + " " + anyCallback.TypeName);
        sb.AppendLine(typeIndent + "{");

        for (var i = 0; i < callbacks.Length; i++)
        {
            if (i > 0)
                sb.AppendLine();

            var c = callbacks[i];
            sb.AppendLine($"{memberIndent}private static readonly global::DataFusionSharp.Interop.NativeMethods.Callback {c.Name}Delegate = {c.Name};");
            sb.AppendLine($"{memberIndent}{c.Accessibility} static readonly global::System.IntPtr {c.Name}Handle = global::System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate({c.Name}Delegate);");
        }

        sb.AppendLine(typeIndent + "}");

        if (hasNamespace)
            sb.AppendLine("}");

        return sb.ToString();
    }
    
    private sealed class CallbackDesc(
        string ns,
        string typeName,
        string typeModifiers,
        string name,
        string accessibility)
    {
        public string Namespace { get; } = ns;
        public string TypeName { get; } = typeName;
        public string TypeFullName => string.IsNullOrEmpty(Namespace) ? TypeName : $"{Namespace}.{TypeName}";
        public string TypeModifiers { get; } = typeModifiers;
        public string Name { get; } = name;
        public string Accessibility { get; } = accessibility;
    }
}
